### ISSUE TITLE
TODO list before abstract submission

### ISSUE THREAD

**Issue by arahosu** [Knee-Deep-in-MRI/DeepSegmentation#74]
- [x] Move class 'train' and its helper functions to train folder (Olivia & Joe)
- [x] Integrate 3D models into main.py 
- [x] Integrate training functions from vnet_train.py into main.py (Olivia) 
- [ ] Rewrite evaluation functions to compute the dice coefficient for each cartilage class (multi-class) (Joonsu & Joe)
- [ ] Rewrite all tf.slice operations to use more Pythonic expressions 
- [x] Implement weighted categorical-cross-entropy (compute weights using the distribution of cartilage classes in the training dataset)  (Olivia & Pietro) 
- [x] Refactor visualisation code (everything in vnet_train.py and main.py should be in the same folder/file) (Olivia & Pietro)
- [ ] Rewrite unit tests (Lapo)
