### ISSUE TITLE
TODO List before poster submission @ IWOAI 2020

### ISSUE THREAD

**Issue by arahosu** [Knee-Deep-in-MRI/DeepSegmentation#76]
# Changes to be made in dev_v2 branch
## Essential
- [ ] Replace all tf.slice operations with more Pythonic indexing and slicing operations in Segmentation/train/reshape.py 
- [ ] Rewrite loss functions and metrics to generalise to 2D and 3D 
- [ ] Check that visualise_sample in train.py works with both 2D and 3D data 
- [ ] Rename enable_function to run_eagerly
- [ ] Show metrics for all (verbose=True) or selected (verbose=False) segmentation classes during training/evaluation
- [ ] Unit tests for all models and training/evaluation functions in the pipeline
- [ ] Implement a separate Evaluator class in evaluate folder along with its helper functions
- [ ] Load dataset should return num_classes, or otherwise make less hardcoded

## Optional 
- [ ] Include an option to select training mode ('fully-supervised', 'semi-supervised', 'self-supervised', 'transfer') in Trainer class
- [ ] Implement a function that allows the users to choose colours for multi-class segmentation evaluation (Similar to 'color' argument in matplotlib.pyplot functions)
- [ ] Implement an option to perform k-fold cross validation/bootstrapping to validate model performance in Evaluator classs
- [ ] Write functions for downloading public medical imaging datasets
